### ISSUE TITLE
Context for a proc given as a preference default changed from v3.0 to v3.1

### ISSUE THREAD

**Issue by waiting-for-dev** [solidusio/solidus#4720]
Before v3.1, the proc given as the default value in a preference had its context bound to the initialized instance. That allowed, for example, referencing other preferences. From v3.1., the context is bound to the class.

**Solidus Version**:
v3.2, v3.1, v3.0

**To Reproduce**

On v3.0 you can do the following:

```ruby
Spree::Calculator::FlatRate.preference(:foo, :string, default: -> { preferred_currency })
a = Spree::Calculator::FlatRate.new
a.preferred_foo #=> "USD"
```

However, on Solidus v3.1:

```ruby
Spree::Calculator::FlatRate.preference(:foo, :string, default: -> { preferred_currency })
a = Spree::Calculator::FlatRate.new
# undefined local variable or method `preferred_currency' for main:Object (NameError)
```

**Current behavior**
The proc is bound to the class context, so a `NameError` is raised because the generated `preferred_` methods are not found.

**Expected behavior**
It should keep working as in v3.0.

**Additional context**
First reported on Slack: https://solidusio.slack.com/archives/C0JBKDF35/p1668417688273419

**Comment by Roddoric** [comment]
I did a git bisect with the example above and found the commit introducing the behavior change
https://github.com/solidusio/solidus/commit/b897eccb6cdd8235d782275e9df069d95474cd6b

I'll try yo look into it has I need it fixed to update our Solidus version

**Comment by waiting-for-dev** [comment]
I also suspected of that commit, but looking to the diff I don't see how it could break that 🤷 Thanks for looking into it, I'm curious about what's the source of the problem here 🙂

**Comment by Roman2K** [comment]
The culprit does indeed seem to be that the commit found by @Roddoric.

It changes the context of execution of the default block when [defining the default getter method](https://github.com/solidusio/solidus/commit/b897eccb6cdd8235d782275e9df069d95474cd6b#diff-1d7628c9b0c063921fa05554bc947bcd7d512427a47f6e7d709256ccd66e3601R63):

Before that commit, the default block was passed as method body, so its execution context was the "preferable" instance:

```ruby
define_method preference_default_getter_method(name), &default
```

After that commit, the default block is merely called from another method body, so its execution context is wherever it was created at (before being passed to `preference(...)`):

```ruby
define_method preference_default_getter_method(name) do
  default.call(*context_for_default)
end
```

---

I see 2 solutions (not tested :nerd_face:):

### 1. instance_exec

```ruby
define_method preference_default_getter_method(name) do
  instance_exec(*context_for_default, &default)
end
```

### 2. define_method

Way more verbose: 

```ruby
define_method preference_default_getter_method(name) do
  send(preference_original_default_getter_method(name), *context_for_default)
end

define_method preference_original_default_getter_method(name), &default

# ...

def preference_original_default_getter_method(name)
  "preferred_#{name}_original_default".to_sym
end
```

**Comment by nvandoorn** [comment]
Hey @waiting-for-dev hope you are well. I know this is an old issue but I'm currently trying to clean up any old issues that can be closed. After having a look at #4721, it seems this issue is fixed. Would you feel comfortable closing this issue?

**Comment by waiting-for-dev** [comment]
Sure @nvandoorn, you can close it. Thanks for asking 🙂
